dist: focal
language: python
python:
  - "3.8"

addons:
  postgresql: "13"
  apt:
    packages:
    - postgresql-13
    - postgresql-client-13
before_script:
  - psql -c 'create database travis_ci;' -U postgres

before_install:
  - export DJANGO_SETTINGS_MODULE=sample_api.settings.tests
  - export PIP_USE_MIRRORS=true
install:
  - pip install -r requirements.txt
  - pip install -r requirements-tests.txt
script: python manage.py test

notifications:
  email:
    recipients:
      - contact@fabienloffredo.com
    on_success: change
    on_failure: always
