version: "3"

services:
  postgresql:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql

  rabbitmq:
    image: rabbitmq:3.13.4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq-definitions.json:/etc/rabbitmq/definitions.json

  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
      - rabbitmq
    container_name: sample_api_back

  celery:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.backend
    command: celery -A sample_api worker -l info
    volumes:
      - .:/app
    depends_on:
      - postgresql
      - rabbitmq
    container_name: sample_api_celery

volumes:
  postgresql:
