version: '3'

services:

  postgresql:
    image: postgres:13.1
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql:/var/lib/postgresql

  rabbitmq:
    image: rabbitmq:3.8.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq-definitions.json:/etc/rabbitmq/definitions.json

  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.backend
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: '/app/'
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
    container_name: sample_api_back

volumes:
  postgresql:
