target-version = "py312"
extend-exclude = [".git", "*migrations*", "*venv*", "*env*"]

[lint]
select = [
    # pycodestyle
    "E",
    "W",
    # mccabe
    "C90",
    # Pyflakes
    "F",
    # isort
    "I",
    # pep8-naming
    "N",
    # pyupgrade
    "UP",
    # flake8-boolean-trap,
    "FBT",
    # flake8-bugbear
    "B",
    # flake8-builtins
    "A",
    # flake8-comprehensions
    "C4",
    # flake8-datetimez
    "DTZ",
    # flake8-debugger
    "T100",
    # flake8-django
    "DJ",
    # flake8-future-annotations
    "FA",
    # flake8-import-conventions
    "ICN",
    # flake8-logging
    "LOG",
    # flake8-logging-format
    "G",
    # flake8-print
    "T20",
    # flake8-return
    "RET",
    # flake8-tidy-imports
    "TID",
    # flake8-gettext
    "INT",
    # flake8-unused-arguments
    "ARG",
    # flake8-use-pathlib
    "PTH",
    # flake8-simplify
    "SIM",
    # eradicate
    "ERA",
    # pandas-vet
    "PD",
    # tryceratops
    "TRY",
    # flynt
    "FLY",
    # NumPy-specific rules
    "NPY",
    # Perflint
    "PERF",
    # Ruff-specific rules
    "RUF",
]
unfixable = ["F401"]
ignore = ["TRY003"]

[lint.pydocstyle]
convention = "google"

[lint.mccabe]
max-complexity = 10

[lint.isort]
"known-first-party" = ["sample_api", "clients", "tasks"]

[format]
docstring-code-format = true
