# Generated by Django 3.1.4 on 2020-12-13 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_results', '0008_chordcounter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('Heavy', 'Tâche à exécution longue'), ('Light', 'Tâche à exécution rapide'), ('Random', 'Tâche à exécution à durée variable')], max_length=30)),
                ('execution_type', models.CharField(choices=[('Heavy', 'Tâche à exécution longue'), ('Light', 'Tâche à exécution rapide'), ('Random', 'Tâche à exécution à durée variable')], default='async', editable=False, max_length=30)),
                ('celery_task', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, to='django_celery_results.taskresult')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
