# Generated by Django 3.1.4 on 2020-12-10 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_celery_results', '0008_chordcounter'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='celery_task',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, to='django_celery_results.taskresult'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
