# Generated by Django 3.2.12 on 2022-03-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='execution_type',
            field=models.CharField(choices=[('sync', 'Synchrone'), ('async', 'Asynchrone')], default='async', editable=False, max_length=30),
        ),
    ]
